name: Pulumi Python Deployment

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # Stage 1: Setup
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r AWSIACProject/requirements.txt

  # Stage 2: Install Pulumi CLI and Login
  pulumi-setup:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Install Pulumi CLI
        uses: pulumi/action-install-pulumi-cli@v1
        with:
          pulumi-version: latest

      - name: Login to Pulumi
        run: |
          cd AWSIACProject  # Change to the Pulumi directory
          pulumi login
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}

  # Stage 3: Select Stack
  select-stack:
    runs-on: ubuntu-latest
    needs: pulumi-setup
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Select Pulumi stack
        run: |
          cd AWSIACProject
          pulumi stack select pulumidev/pulumidev  
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}

  # Stage 4: Cloud Authentication
  cloud-auth:
    runs-on: ubuntu-latest
    needs: select-stack
    steps:
      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

  # Stage 5: Pulumi Deployment
  deploy:
    runs-on: ubuntu-latest
    needs: cloud-auth
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Deploy infrastructure using Pulumi
        run: |
          cd AWSIACProject  # Change to the Pulumi directory
          pulumi up --yes
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
