name: Pulumi Python Deployment

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # Stage 1: Setup
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

  # Stage 2: Install Pulumi CLI and Login
  pulumi-setup:
    runs-on: ubuntu-latest
    needs: setup  # Dependent on the setup stage
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Install Pulumi CLI
        uses: pulumi/action-install-pulumi-cli@v1  # Correct action for installing Pulumi CLI
        with:
          pulumi-version: latest  # Install the latest version of Pulumi

      - name: Login to Pulumi
        run: pulumi login
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}  # Your Pulumi access token

   # Stage 3: Select Stack
  select-stack:
    runs-on: ubuntu-latest
    needs: pulumi-setup  # Dependent on the pulumi-setup stage
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Select Pulumi stack
        run: pulumi stack select awsdev  # Replace 'dev' with your actual stack name
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }} 

  # Stage 4: Cloud Authentication
  cloud-auth:
    runs-on: ubuntu-latest
    needs: select-stack  # Dependent on the select-stack stage
    steps:
      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # Alternatively for Azure or GCP, replace this with your cloud provider authentication

  # Stage 5: Pulumi Deployment
  deploy:
    runs-on: ubuntu-latest
    needs: cloud-auth  # Dependent on the cloud-auth stage
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Deploy infrastructure using Pulumi
        run: pulumi up --yes
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
